// Batch pipeline types — prospects input + snapshot index output

export type RestaurantType =
  | "fast_casual"
  | "fast_food"
  | "pizza"
  | "bar_grill"
  | "fine_dining"
  | "cafe"
  | "breakfast"
  | "mexican"
  | "asian"
  | "seafood"
  | "other";

export interface BatchProspect {
  /** URL-safe slug — used as snapshot filename prefix */
  id: string;
  name: string;
  menu_url: string;
  type: RestaurantType;
  /** Copper CRM record ID — null until linked */
  crm_id: string | null;
  notes: string | null;
}

export interface ProspectsFile {
  version: "1";
  prospects: BatchProspect[];
}

export type SnapshotStatus = "ready" | "processing" | "failed" | "stale";

/** How item images were sourced for this snapshot */
export type AssetSource =
  | "pack"   // matched from a purchased icon pack
  | "ai"     // generated by Claude
  | "none";  // no images (POS defaults)

export interface SnapshotEntry {
  prospect_id: string;
  name: string;
  /** Path to .sql file, relative to demo-builder root */
  file: string;
  created_at: string;
  item_count: number;
  group_count: number;
  /** POS schema version this snapshot targets, e.g. "4.28.2" */
  schema_version: string;
  status: SnapshotStatus;
  menu_url: string;
  extraction_id: string | null;
  asset_source: AssetSource;
  /** Populated when status === "failed" */
  error: string | null;
}

export interface SnapshotIndex {
  version: "1";
  snapshots: SnapshotEntry[];
}
